export const STORE_CLUB_CATEGORIES = 'STORE_CLUB_CATEGORIES'
export const CLUB_CATEOGRY_LOADING = 'CLUB_CATEOGRY_LOADING'
export const TOGGLE_SHOW_VERIFY_MODAL = 'TOGGLE_SHOW_VERIFY_MODAL';
export const TOGGLE_SHOW_BROWSE_MODAL = 'TOGGLE_SHOW_BROWSE_MODAL'
export const UPDATE_LOCATION = 'UPDATE_LOCATION'